/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 keyboardscene.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function KeyboardScene(props) {
  const { nodes, materials } = useGLTF('/model/keyboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Desk.geometry} material={materials.Desk} scale={0.2} />
      <mesh geometry={nodes.Boxes.geometry} material={materials.Boxes} scale={0.2} />
      <mesh geometry={nodes.Paper.geometry} material={materials.Paper} scale={0.2} />
      <mesh geometry={nodes.Books.geometry} material={materials.Books} scale={0.2} />
      <mesh geometry={nodes.Notebook.geometry} material={materials.Notebook} scale={0.2} />
      <mesh geometry={nodes.Notebook_wire.geometry} material={materials.WIre} scale={0.2} />
      <mesh geometry={nodes.Pen.geometry} material={materials.Pen} scale={0.2} />
      <mesh geometry={nodes.Eraser.geometry} material={materials.Eraser} position={[-0.11, 0, 0.09]} scale={0.2} />
      <mesh geometry={nodes.Dish.geometry} material={materials.Cup} scale={0.2} />
      <group position={[0.05, 0, 0.03]} scale={0.2}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0.44, 0, 0]} scale={[1, 1, 1.64]} />
      <mesh geometry={nodes.Boxes001.geometry} material={materials['Material.004']} scale={0.2} />
      <mesh geometry={nodes.PC_Speaker.geometry} material={materials.PC_Speakers} />
      <mesh geometry={nodes.Keyboard_wire.geometry} material={materials.WIre} />
      <mesh geometry={nodes.PC_Mouse.geometry} material={materials.PC_Mouse} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mouse_wire.geometry} material={materials.WIre} position={[0, 0, -0.47]} />
      <mesh geometry={nodes.Mousepad.geometry} material={materials.Mousepad} />
      <mesh geometry={nodes.AKAI_LP.geometry} material={materials['03 - Default']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.c2.geometry} material={materials['03 - Default']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.C.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['c#1'].geometry} material={materials['Material.002']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['d#'].geometry} material={materials['Material.002']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['f#'].geometry} material={materials['Material.002']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['g#'].geometry} material={materials['Material.002']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['a#'].geometry} material={materials['Material.002']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.d.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.e.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.f.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.g001.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.a.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.b001.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.C001.geometry} material={materials['Material.001']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['c#1001'].geometry} material={materials['Material.002']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['d#001'].geometry} material={materials['Material.002']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['f#001'].geometry} material={materials['Material.002']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['g#001'].geometry} material={materials['Material.002']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes['a#001'].geometry} material={materials['Material.002']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.d001.geometry} material={materials['Material.001']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.e001.geometry} material={materials['Material.001']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.f001.geometry} material={materials['Material.001']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.g002.geometry} material={materials['Material.001']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.a001.geometry} material={materials['Material.001']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.b002.geometry} material={materials['Material.001']} position={[0.12, 0.43, -0.16]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.c2001.geometry} material={materials['Material.001']} position={[0.12, 0.43, 0]} rotation={[0, Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.PC_Keyboard} />
      <mesh geometry={nodes.Cube005_1.geometry} material={materials.Keyboard_light} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.PC_Monitor} />
      <mesh geometry={nodes.Cube004_1.geometry} material={materials.PC_Screen} />
    </group>
  )
}

useGLTF.preload('/model/keyboard.glb')


